project:
  type: website
  output-dir: docs
website:
  title: "A Journey Within"
  
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: papers.qmd
        text: Papers
      - href: workshops.qmd
        text: Workshops
      - href: blog.qmd
        text: Blog
      - about.qmd
  sidebar:
    style: "docked"
    logo: "./images/user_image.png"
    search: true
    collapse-level: 2
    contents:
      - icon: github
        text: Github
        url: https://github.com
      - icon: twitter
        text: Twitter
        url: https://twitter.com
      - icon: Email
      - text: "Email"
        url: mailto:siju.swamy@saintgits.org
      - text: "ORCID"
        url: https://orcid.org/<orcid-id>
      - text: "Google Scholar"
        url: https://scholar.google.com/citations?user=<google-scholar-user>
  announcement: 
    icon: info-circle
    dismissable: true
    content: "**Alert** - This Website is created using `Quarto` and Published as Github Pages"
    type: primary
    position: below-navbar
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
  


